// Auto-generated by server.py — do not edit manually.
// Updated every time the Admin Panel saves changes.
window.MEMBERS_DATA = {
  "current_members": [
    {
      "id": "1782903660616",
      "name": "Anuj Prakash",
      "role": "President",
      "class": "12-G",
      "year": "2026-27",
      "department": "Coordination Department",
      "is_head": true,
      "image": "public/anuj-prakash-1782903660289.jpg"
    },
    {
      "id": "1782903673754",
      "name": "Nabeel Jami",
      "role": "Vice-President",
      "class": "12-F",
      "year": "2026-27",
      "department": "Tech Department",
      "is_head": true,
      "image": "public/nabeel-jami-1782903673746.jpg"
    },
    {
      "id": "1782903697424",
      "name": "Pranjal Sinha",
      "role": "Vice-President",
      "class": "12-F",
      "year": "2026-27",
      "department": "Coordination Department",
      "is_head": false,
      "image": "public/pranjal-sinha-1782903697418.jpg"
    },
    {
      "id": "1782903722008",
      "name": "Atharva Singh",
      "role": "Head of Management",
      "class": "12-F",
      "year": "2026-27",
      "department": "Planning and Management Department",
      "is_head": true,
      "image": "public/atharva-singh-1782903721949.jpg"
    },
    {
      "id": "1782903740405",
      "name": "Pratiksha Bharadwaj",
      "role": "Head of Graphics",
      "class": "12-G",
      "year": "2026-27",
      "department": "Graphics Department",
      "is_head": true,
      "image": "public/pratiksha-bharadwaj-1782903740396.jpg"
    },
    {
      "id": "1782903758502",
      "name": "Tanvi",
      "role": "Head of PR & Social Media",
      "class": "12-H",
      "year": "2026-27",
      "department": "Social Media Department",
      "is_head": true,
      "image": "public/tanvi-1782903758496.jpg"
    }
  ],
  "past_members": [
    {
      "id": "12",
      "name": "Utkersh Kumar",
      "role": "Developer",
      "class": "12-E",
      "year": "2025-2026",
      "image": "public/utkersh-kumar.png"
    },
    {
      "id": "11",
      "name": "Ashwin Raj",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/ashwin-raj.png"
    },
    {
      "id": "10",
      "name": "Shrijan Prakash",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/shrijan-prakash.png"
    },
    {
      "id": "9",
      "name": "Shivansh",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/shivansh.png"
    },
    {
      "id": "8",
      "name": "Sachin Aditya Prakash",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/sachin-aditya-prakash.png"
    },
    {
      "id": "7",
      "name": "Amogh",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/amogh.png"
    },
    {
      "id": "6",
      "name": "Dev Padia",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/dev-padia.png"
    },
    {
      "id": "5",
      "name": "Kavya Jain",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/kavya-jain.png"
    },
    {
      "id": "4",
      "name": "Shreeja",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/shreeja.png"
    },
    {
      "id": "2",
      "name": "Aayushman Bhardwaj",
      "role": "Council Member",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/aayushman-bhardwaj.png"
    },
    {
      "id": "1",
      "name": "Ankit Mohapatra",
      "role": "President & Founder",
      "class": "12-I",
      "year": "2025-2026",
      "image": "public/ankit-mohapatra.png"
    }
  ]
};
